# 一起作业 App 广告拦截规则
# Quantumult X 分流规则

HOST,adimage.bwton.com,REJECT
HOST,sdk.1rtb.net,REJECT
HOST,dc.sigmob.cn,REJECT
HOST,win.gdt.qq.com,REJECT
HOST,ad.baihemob.com,REJECT
HOST,sdk.beizi.biz,REJECT
HOST,s3plus.meituan.net,REJECT
HOST,log.17zuoye.net,REJECT
HOST,sdklog.zhangyuyidong.cn,REJECT
HOST,impdsp.meituan.com,REJECT
HOST,ssp.1rtb.com,REJECT
HOST,tk.anythinktech.com,REJECT
HOST,ca-manager.17zuoye.com,REJECT
