# 一起作业 App 广告拦截规则
# Quantumult X 重写规则

hostname = adimage.bwton.com, sdk.1rtb.net, dc.sigmob.cn, win.gdt.qq.com, ad.baihemob.com, sdk.beizi.biz, s3plus.meituan.net, log.17zuoye.net, sdklog.zhangyuyidong.cn, impdsp.meituan.com, ssp.1rtb.com, tk.anythinktech.com, ca-manager.17zuoye.com

^https?:\/\/adimage\.bwton\.com url reject-dict
^https?:\/\/sdk\.1rtb\.net url reject-dict
^https?:\/\/dc\.sigmob\.cn url reject-dict
^https?:\/\/win\.gdt\.qq\.com url reject-dict
^https?:\/\/ad\.baihemob\.com url reject-dict
^https?:\/\/sdk\.beizi\.biz url reject-dict
^https?:\/\/s3plus\.meituan\.net url reject-dict
^https?:\/\/log\.17zuoye\.net url reject-dict
^https?:\/\/sdklog\.zhangyuyidong\.cn url reject-dict
^https?:\/\/impdsp\.meituan\.com url reject-dict
^https?:\/\/ssp\.1rtb\.com url reject-dict
^https?:\/\/tk\.anythinktech\.com url reject-dict
^https?:\/\/ca-manager\.17zuoye\.com url reject-dict
